<?php
require_once __DIR__ . '/bootstrap.php';
ensure_logged_in();
$keyword = trim($_GET['q'] ?? '');
$editId = (int)($_GET['edit'] ?? 0);
if ($keyword !== '') {
    $pasienList = db_fetch_all("SELECT * FROM pasien WHERE no_rm LIKE ? OR nama LIKE ? OR telepon LIKE ? ORDER BY id DESC", ["%$keyword%","%$keyword%","%$keyword%"]);
} else {
    $pasienList = db_fetch_all("SELECT p.*, (SELECT COUNT(*) FROM kunjungan k WHERE k.pasien_id=p.id) AS total_kunjungan, (SELECT COUNT(*) FROM invoice i WHERE i.pasien_id=p.id) AS total_invoice FROM pasien p ORDER BY p.id DESC LIMIT 300");
}
$editData = $editId > 0 ? db_fetch_one("SELECT * FROM pasien WHERE id=?", [$editId]) : null;
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Data Pasien</title>
<style>*{box-sizing:border-box;font-family:Inter,Arial,sans-serif}body{margin:0;background:#f8fbff;color:#0f172a}.wrap{max-width:1360px;margin:0 auto;padding:24px}.head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;flex-wrap:wrap}.card{background:#fff;border:1px solid #e2e8f0;border-radius:24px;padding:22px;box-shadow:0 14px 30px rgba(15,23,42,.06);margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.full{grid-column:1/-1}input,select,textarea,button{width:100%;padding:13px 14px;border:1px solid #cbd5e1;border-radius:14px}.btn,button{background:#0f172a;color:#fff;text-decoration:none;display:inline-block;text-align:center;border:none;font-weight:700;cursor:pointer}.btn.secondary{background:#475569}.table-wrap{overflow:auto;-webkit-overflow-scrolling:touch}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:12px;border-bottom:1px solid #e2e8f0;vertical-align:top}.actions a{display:inline-block;margin:4px 6px 0 0;padding:8px 10px;border-radius:12px;text-decoration:none;background:#eff6ff;color:#1d4ed8}.muted{color:#64748b;font-size:13px}.topnav{display:flex;gap:10px;flex-wrap:wrap}.search{display:flex;gap:10px;flex-wrap:wrap}@media(max-width:860px){.grid{grid-template-columns:1fr}}</style></head><body><div class="wrap">
<div class="head"><div><h1 style="margin:0 0 8px">Data Pasien</h1><div class="muted">Master pasien terintegrasi ke kunjungan, odontogram, resume medis, surat sakit, dan billing.</div></div><div class="topnav"><a class="btn secondary" href="dashboard.php">Dashboard</a><a class="btn" href="invoice.php">Billing</a></div></div>
<div class="card"><?php flash_message(); ?><form class="search" method="get"><input type="text" name="q" value="<?= e($keyword) ?>" placeholder="Cari No RM / nama / telepon" style="flex:1;min-width:260px"><button type="submit" style="width:auto;padding:0 18px">Cari</button><a class="btn secondary" href="pasien.php" style="padding:13px 18px">Reset</a></form></div>
<div class="card"><h2 style="margin-top:0"><?= $editData ? 'Edit Pasien' : 'Tambah Pasien' ?></h2><form method="post" action="simpan_pasien.php"><input type="hidden" name="id" value="<?= (int)($editData['id'] ?? 0) ?>"><div class="grid"><div><label>No RM</label><input type="text" name="no_rm" required value="<?= e($editData['no_rm'] ?? next_rm()) ?>"></div><div><label>NIK</label><input type="text" name="nik" value="<?= e($editData['nik'] ?? '') ?>"></div><div><label>Nama Pasien</label><input type="text" name="nama" required value="<?= e($editData['nama'] ?? '') ?>"></div><div><label>Jenis Kelamin</label><select name="jk"><option value="L" <?= (($editData['jk'] ?? '') === 'L') ? 'selected' : '' ?>>Laki-laki</option><option value="P" <?= (($editData['jk'] ?? '') === 'P') ? 'selected' : '' ?>>Perempuan</option></select></div><div><label>Tempat Lahir</label><input type="text" name="tempat_lahir" value="<?= e($editData['tempat_lahir'] ?? '') ?>"></div><div><label>Tanggal Lahir</label><input type="date" name="tanggal_lahir" value="<?= e($editData['tanggal_lahir'] ?? '') ?>"></div><div><label>Telepon</label><input type="text" name="telepon" value="<?= e($editData['telepon'] ?? '') ?>"></div><div class="full"><label>Alamat</label><textarea name="alamat" rows="3"><?= e($editData['alamat'] ?? '') ?></textarea></div><div class="full"><label>Alergi / Catatan Penting</label><textarea name="alergi" rows="2"><?= e($editData['alergi'] ?? '') ?></textarea></div></div><div style="margin-top:14px;display:flex;gap:10px;flex-wrap:wrap"><button type="submit" style="width:auto;padding:13px 18px">Simpan Pasien</button><?php if ($editData): ?><a class="btn secondary" style="padding:13px 18px" href="pasien.php">Batal Edit</a><?php endif; ?></div></form></div>
<div class="card"><h2 style="margin-top:0">Daftar Pasien</h2><div class="table-wrap"><table class="table"><thead><tr><th>No RM</th><th>Nama</th><th>Telepon</th><th>Riwayat</th><th>Aksi</th></tr></thead><tbody><?php foreach ($pasienList as $p): ?><tr><td><strong><?= e($p['no_rm']) ?></strong><div class="muted"><?= e($p['jk']) ?> • <?= e($p['tanggal_lahir']) ?></div></td><td><?= e($p['nama']) ?><div class="muted"><?= e($p['alamat']) ?></div></td><td><?= e($p['telepon']) ?></td><td><?= (int)($p['total_kunjungan'] ?? 0) ?> kunjungan<br><?= (int)($p['total_invoice'] ?? 0) ?> invoice</td><td class="actions"><a href="pasien.php?edit=<?= (int)$p['id'] ?>">Edit</a><a href="kunjungan.php?pasien_id=<?= (int)$p['id'] ?>">Kunjungan</a><a href="invoice.php?pasien_id=<?= (int)$p['id'] ?>">Billing</a><a href="pasien_history.php?pasien_id=<?= (int)$p['id'] ?>">Riwayat</a></td></tr><?php endforeach; if(!$pasienList): ?><tr><td colspan="5">Belum ada data pasien.</td></tr><?php endif; ?></tbody></table></div></div></div></body></html>